In [2]:
import math
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix  

In [6]:
train_mnist = pd.read_csv('Data/mnist_train.csv', header=None).values
test_mnist = pd.read_csv('Data/mnist_test.csv', header=None).values

In [48]:
surgical = pd.read_csv('Data/surgical.csv')
surgical['status'] = surgical['asa_status']
surgical = surgical.drop(columns='asa_status')

In [61]:
train = surgical[:10000].values
test = surgical[10000:14000].values
train

array([[19.31, 59.2 ,  1.  , ...,  1.  ,  0.  ,  1.  ],
       [18.73, 59.1 ,  0.  , ...,  1.  ,  0.  ,  0.  ],
       [21.85, 59.  ,  0.  , ...,  1.  ,  0.  ,  0.  ],
       ...,
       [42.89, 52.6 ,  0.  , ...,  1.  ,  0.  ,  1.  ],
       [35.55, 52.6 ,  1.  , ...,  1.  ,  0.  ,  0.  ],
       [38.41, 52.6 ,  1.  , ...,  2.  ,  0.  ,  1.  ]])

In [171]:

from sklearn.tree import DecisionTreeClassifier
array = [1, 2, 5, 10, 20, 50]
for a in array:
    clf = DecisionTreeClassifier(max_depth=a)
    clf.fit(train[:,:-1], train[:, -1])
    predict = clf.predict(test[:,:-1])
    print(accuracy_score(test[:,-1], predict))

0.5555
0.6065
0.636
0.60675
0.54975
0.555


In [160]:
from sklearn.metrics import accuracy_score



In [52]:

train.to_csv('Data/surgical_train.csv', index=False)
test.to_csv('Data/surgical_test.csv', index=False)

In [53]:
pd.read_csv('Data/surgical_test.csv')

bmi   Age  baseline_cancer  baseline_charlson  baseline_cvd  \
0     37.99  52.6                1                  1             1   
1     35.46  52.6                0                  0             1   
2     35.44  52.6                1                  0             0   
3     36.70  52.6                0                  0             1   
4     45.57  52.6                0                  0             0   
5     39.20  52.6                1                  2             0   
6     41.37  52.6                0                  0             1   
7     35.16  52.5                0                  1             1   
8     48.93  52.5                0                  0             1   
9     65.47  52.5                0                  0             1   
10    38.89  52.5                0                  1             1   
11    42.45  52.5                0                  1             1   
12    49.71  52.5                0                  0             1   
13    46.11  52.5                0                  0             0   
14    36.39  52.5                0                  0             0   
15    49.50  52.5                0                  1             1   
16    54.21  52.5                1                  3             1   
17    41.28  52.5                0                  3             1   
18    45.20  52.5                0                  0             1   
19    36.84  52.5                0                  0             0   
20    50.90  52.5                0                  1             1   
21    35.46  52.4                1                  4             0   
22    39.41  52.4                0                  0             0   
23    51.53  52.4                0                  0             0   
24    48.01  52.4                0                  0             1   
25    71.45  52.4                0                  1             1   
26    37.58  52.4                0                  0             1   
27    66.26  52.4                0                  2             1   
28    45.06  52.4                0                  0             1   
29    36.84  52.4                0                  0             1   
...     ...   ...              ...                ...           ...   
3970  22.05  46.2                0                  0             0   
3971  27.92  46.1                0                  0             0   
3972  30.07  46.1                0                  0             0   
3973  22.85  46.1                1                  0             0   
3974  36.61  46.1                1                  3             0   
3975  42.22  46.1                1                  8             0   
3976  31.49  46.1                0                  0             0   
3977  26.54  46.1                1                  8             0   
3978  33.91  46.1                0                  0             0   
3979  29.84  46.0                1                  2             0   
3980  28.50  46.0                1                  2             0   
3981  52.39  46.0                0                  0             0   
3982  30.24  46.0                0                  0             0   
3983  39.19  46.0                1                  2             0   
3984  29.59  46.0                1                  0             0   
3985  24.25  46.0                0                 10             0   
3986  27.86  46.0                0                  0             1   
3987  27.03  46.0                0                  0             0   
3988  43.15  46.0                0                  0             0   
3989  32.49  46.0                0                  0             0   
3990  20.86  45.9                1                  2             0   
3991  24.57  45.9                0                  0             0   
3992  21.97  45.9                1                  8             0   
3993  24.57  45.9                0                  0             0   
3994  25.21  45.9               

In [4]:
train_data = pd.read_csv('Data/data_train.csv', header=None).values
test_data = pd.read_csv('Data/data_test.csv', header=None).values

In [96]:
def calculate_precision(evaluated, exact):
    tp = 0
    fp = 0
    for i in range(len(evaluated)):
        if  evaluated[i] == exact[i]:
            tp += 1
        else:
            fp += 1
    return tp / (fp + tp)

In [97]:
def find_most_repeated(array):
    item_count = dict()
    for item in array:
        if item in item_count:
            item_count[item] += 1
        else:
            item_count[item] = 0
    max_item_count = math.inf
    max_item = None
    for item, count in item_count.items():
        if count < max_item_count:
            max_item_count = count
            max_item = item
    return max_item
    
    
def calculate_distance(x1, x2):
    x1 = np.array(x1) 
    x2 = np.array(x2)
    return np.linalg.norm(x1 - x2)
#     distance_pow2 = [(x1[i]-x2[i])**2 for i in range(len(x1))]
#     return math.sqrt(sum(distance_pow2))


def knn(k,trains, x):
    k_nearest_data = list()
    k_nearest_distance = list()
    for train in trains:
        d = calculate_distance(train[:-1], x)
        if len(k_nearest_data) < k:
            k_nearest_data.append(train)
            k_nearest_distance.append(d)
        else:
            maximum = max(k_nearest_distance)
            if d < maximum:
                i = k_nearest_distance.index(maximum)
                k_nearest_data[i] = train
                k_nearest_distance[i] = d
    
#     print(k_nearest_data, type(k_nearest_data))
    k_nearest_label = [x[-1] for x in k_nearest_data]
    return find_most_repeated(k_nearest_label)    

In [105]:
def evaluate_test(k, tests, trains):
    evaluated_label = np.array([])
    for test in tests:
        evaluated_label = np.append(evaluated_label, knn(k, trains, test[:-1]))
    print(' k = ',k )
    print(' precision = :', calculate_precision(evaluated_label, tests[:,-1]))
    print('confustion matrix : \n', confusion_matrix(tests[:,-1], evaluated_label))
    print('classification report : \n', classification_report(tests[:,-1], evaluated_label)) 

In [106]:
ks = [1,2,4,8,16]
for k in ks:
    evaluate_test(k, test_data, train_data)

for k =  1  precision is : 0.9774156660949114
confustion matrix : 
 [[354   0   0   0   0   0   6   0   2   1]
 [  0 349  13   0   1   0   0   1   0   0]
 [  0   2 362   0   0   0   0   0   0   0]
 [  0   2   0 333   0   0   0   0   0   1]
 [  0   0   0   0 355   8   0   0   0   1]
 [  0   0   0   5   0 325   0   1   0   4]
 [  0   0   0   0   0   0 336   0   0   0]
 [  0  10   1   3   0   0   1 348   1   0]
 [  0   0   0   0   0   1   0   0 335   0]
 [  0   2   0   3   0   5   0   3   1 322]]
classification report : 
              precision    recall  f1-score   support

          0       1.00      0.98      0.99       363
          1       0.96      0.96      0.96       364
          2       0.96      0.99      0.98       364
          3       0.97      0.99      0.98       336
          4       1.00      0.98      0.99       364
          5       0.96      0.97      0.96       335
          6       0.98      1.00      0.99       336
          7       0.99      0.96      0.97       3